logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5marker %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5marker %-5level %logger{36} - %msg%n"

ais:
  connector:
    web-socket-port: 8100
    socket:
      timeout: 10000
      keep-alive-message: "$PSTT,01\r\n"
      keep-alive-response-message: "$PSTT,01*2E"
      keep-alive-initial-delay: 20000
      keep-alive-fixed-delay: 10000
      keep-alive-timeout: 30000
      logoff-message: "$PSTT,FF\r\n"